name: Deploy Laravel Project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.0'

    - name: Create deployment structure and compress
      run: |
        mkdir -p deploy/transit/site
        mv public/* deploy/transit/
        mv * deploy/transit/site/ || true
        mv deploy/transit/site/public/* deploy/transit/ || true
        cp .env.example deploy/transit/site/.env
        cd deploy
        tar -czf deploy.tar.gz transit

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: istam.tech
        username: u992053974
        password: Sadenachbi@13
        local-dir: ./deploy/
        server-dir: /public_html/

    - name: Decompress, install dependencies and setup
      uses: appleboy/ssh-action@master
      with:
        host: 195.35.49.232
        username: u992053974
        password: Sadenachbi@13
        port: 65002
        script: |
          cd /public_html
          tar -xzf deploy.tar.gz
          rm deploy.tar.gz
          cd transit/site
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          php artisan migrate
          php artisan storage:link
          php artisan optimize
