name: Deploy Laravel Project

on:
  push:
    branches: [ main ]  # ou le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: istam.tech
        username: u992053974
        password: Sadenachbi@13
        server-dir: /public_html/transit/

    - name: Execute post-deployment commands
      uses: appleboy/ssh-action@master
      with:
        host: 195.35.49.232
        username: u992053974
        password: Sadenachbi@13
        port: 65002
        script: |
          echo "Current directory:"
          pwd
          echo "Changing to /home/u992053974/public_html/transit:"
          cd /home/u992053974/public_html/transit || { echo "Failed to change directory"; exit 1; }
          echo "Current directory after cd:"
          pwd
          echo "Listing current directory contents:"
          ls -la
          echo "Installing dependencies:"
          composer install --no-interaction --prefer-dist --optimize-autoloader
          echo "Generating application key:"
          php artisan key:generate
          echo "Running migrations:"
          php artisan migrate --force
          echo "Caching configuration:"
          php artisan config:cache
          echo "Caching routes:"
          php artisan route:cache
          echo "Caching views:"
          php artisan view:cache
          echo "Setting permissions:"
          chmod -R 775 storage bootstrap/cache
